name: Secret Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check dummy secret
        env:
          TEST_SECRET: ${{ secrets.SECURITY_TEST }}
        run: |
          if [ -n "$TEST_SECRET" ]; then
            echo "SECRET_AVAILABLE=yes"
          else
            echo "SECRET_AVAILABLE=no"
          fi
