name: Pull Request Target Test

on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check dummy secret
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          if [ -n "$TEST_SECRET" ]; then
            echo "DUMMY_SECRET_AVAILABLE=yes"
          else
            echo "DUMMY_SECRET_AVAILABLE=no"
          fi
