name: Call Integrity Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call:
    uses: jaserjasar/Test/.github/workflows/reusable-integrity-test.yml@8276e6b86a4ec22d678f811872cccdb7f53897cc
